[package]
name = "reverse-gol"
version = "0.1.0"
edition = "2024"

[dependencies]
smallvec = "1.15"
bitvec = "1.0"
metrohash = "1.0"
rayon = "1.0"
num = "0.4"
typenum = { version = "1.0", features = ["const-generics"] }

[profile.dev]
opt-level = 2
